hibernate:
  event:
    listener:
      enabled: true
spring:
  main:
    allow-bean-definition-overriding : true
  application:
    name: trigger_poc
  jpa:
    enable: true
    generate-ddl: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://searchly:searchly@localhost:27020/local?authSource=searchly
      database: searchly
  datasource:
    enable: true
    basePackages: com.saisonomni.com.trigger_poc.entity.repo
    baseModel: com.saisonomni.com.trigger_poc.entity
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5436/mydb
    url: jdbc:postgresql://localhost:5436/mydb
    username: aniket
    password: aniket
    platform: postgresql
    generate-ddl: true
    database: POSTGRESQL
    show-sql: true
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      ddlAuto: none
      showSql: true
      schema: ${spring.application.name}
    hibernate:
      ddl-auto: create-drop
      default_schema: appform
service:
  ehs:
    url: "http://localhost:8088"
    endpoint:
      send: "/event-handling/event"
      register: "/event-handling/registerConsumer"
rabbit:
  host: localhost
  port: 5672
  username: admin
  password: admin
server:
  port: 7777